CC = gcc
CFLAGS = -Wall -Wextra

.PHONY: all clean

all: ./output/program

TARGET = main

./output/program: $(TARGET).o arvore.o
	$(CC) $(CFLAGS) -o $@ $^

$(TARGET).o: $(TARGET).c arvoreB.h
	$(CC) $(CFLAGS) -c $^

arvore.o: arvoreB.c arvoreB.h
	$(CC) $(CFLAGS) -c $^

clean:
	rm -f ./*.o ./output/$(TARGET)
